"""remove_game_field

Revision ID: 68a6be6314a7
Revises: b2396228c903
Create Date: 2025-05-05 16:21:18.091668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68a6be6314a7'
down_revision: Union[str, None] = 'b2396228c903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gamestats_game_id_key', 'gamestats', type_='unique')
    op.drop_constraint('gamestats_game_id_fkey', 'gamestats', type_='foreignkey')
    op.drop_column('gamestats', 'game_id')
    op.drop_constraint('playerstats_player_id_game_id_key', 'playerstats', type_='unique')
    op.drop_constraint('playerstats_game_id_fkey', 'playerstats', type_='foreignkey')
    op.drop_constraint('playerstats_player_id_fkey', 'playerstats', type_='foreignkey')
    op.drop_column('playerstats', 'player_id')
    op.drop_column('playerstats', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerstats', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('playerstats', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('playerstats_player_id_fkey', 'playerstats', 'player', ['player_id'], ['id'])
    op.create_foreign_key('playerstats_game_id_fkey', 'playerstats', 'game', ['game_id'], ['id'])
    op.create_unique_constraint('playerstats_player_id_game_id_key', 'playerstats', ['player_id', 'game_id'])
    op.add_column('gamestats', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('gamestats_game_id_fkey', 'gamestats', 'game', ['game_id'], ['id'])
    op.create_unique_constraint('gamestats_game_id_key', 'gamestats', ['game_id'])
    # ### end Alembic commands ###
