"""add_gameid_field

Revision ID: 9477b93e3bec
Revises: 68a6be6314a7
Create Date: 2025-05-05 17:08:49.738553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9477b93e3bec'
down_revision: Union[str, None] = '68a6be6314a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamestats', sa.Column('game_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamestats', 'game_id')
    # ### end Alembic commands ###
